Update Jenkinsfiles to match server project.

diff --git a/Jenkinsfile-debian-10-slim-primary b/Jenkinsfile-debian-10-slim-primary
--- a/Jenkinsfile-debian-10-slim-primary
+++ b/Jenkinsfile-debian-10-slim-primary
@@ -94,14 +94,14 @@ pipeline {
         }
       }
     }
-    stage('Run installer on primary') {
+    stage('Run getsf installer on primary') {
       steps {
         script {
           timeout(time: 20, unit: 'MINUTES', activity: true) {
             sh '''  . $WORKSPACE/$BUILD_TAG/ci-environment.sh
                     ssh -i /home/jenkins/id_ci -o StrictHostKeyChecking=no \
                         -o UserKnownHostsFile=/dev/null \
-                        debian@$primary sudo /root/sf-deploy.sh
+                        debian@$primary /tmp/getsf-wrapper
                     echo ""
                     echo ""
                     ssh -i /home/jenkins/id_ci -o StrictHostKeyChecking=no \
@@ -254,13 +254,33 @@ pipeline {
       sh '''  set -x
               . /home/jenkins/sf-ci
               . $WORKSPACE/$BUILD_TAG/ci-environment.sh || true
-              mkdir artifacts
+
+              rm -rf artifacts bundle
+              mkdir -p artifacts bundle
 
               echo "=============================="
-              ssh -i /home/jenkins/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
-                  debian@$primary sudo /srv/shakenfist/venv/bin/clingwrap gather --target /srv/shakenfist/venv/share/clingwrap/shakenfist-ci-failure.cwd --output /tmp/all.zip
-              scp -i /home/jenkins/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
-                  debian@$primary:/tmp/all.zip artifacts/
+              for node in $nodes
+              do
+                echo "=== $node ==="
+                safe_node=$(echo $node | tr "-" "_")
+
+                ssh -i /home/jenkins/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
+                    debian@${!safe_node} sudo /srv/shakenfist/venv/bin/clingwrap gather \
+                    --target /srv/shakenfist/venv/share/clingwrap/shakenfist-ci-failure.cwd --output /tmp/$node.zip
+                scp -i /home/jenkins/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
+                    debian@${!safe_node}:/tmp/$node.zip bundle/
+
+                mkdir -p bundle/$node
+                unzip -v bundle/$node.zip
+
+                # We ignore the exit code of unzip, as it will return 1 if a warning is
+                # emitted during expansion, even though expansion worked correctly. For
+                # example stripping a leading / from paths.
+                unzip bundle/$node.zip -d bundle/$node/ || true
+                rm bundle/$node.zip
+              done
+
+              zip -r artifacts/bundle.zip bundle/*
 
               echo "=============================="
 
@@ -270,11 +290,15 @@ pipeline {
               else
                 sf-client namespace clean --namespace $BUILD_TAG --confirm
               fi
+          '''
 
+          archiveArtifacts artifacts: "artifacts/bundle.zip", fingerprint: true
+
+      sh '''
               rm -rf $WORKSPACE/$BUILD_TAG
           '''
 
-          archiveArtifacts artifacts: 'artifacts/all.zip', fingerprint: true
+
     }
   }
 }
