Update CI to match Shaken Fist.

diff --git a/.github/workflows/functional-tests-debian-11-slim-primary.yml b/.github/workflows/functional-tests-debian-11-slim-primary.yml
--- a/.github/workflows/functional-tests-debian-11-slim-primary.yml
+++ b/.github/workflows/functional-tests-debian-11-slim-primary.yml
@@ -13,7 +13,6 @@ on:
 jobs:
   debian-11-slim-primary:
     runs-on: self-hosted
-    timeout-minutes: 120
     concurrency:
       group: ${{ github.workflow }}-${{ github.ref }}
       cancel-in-progress: true
@@ -47,16 +46,19 @@ jobs:
               base_image=sf://label/ci-images/debian-11 base_image_user=debian" \
               deploy/ansible/ci-topology-slim-primary.yml
 
-      - name: Log github actions buffering status
+      - name: Copy CI tools to primary
         run: |
           . ${GITHUB_WORKSPACE}/ci-environment.sh
           cd ${GITHUB_WORKSPACE}/shakenfist
           scp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
-              -o UserKnownHostsFile=/dev/null \
-              tools/buffer.py debian@$primary:buffer.py
-          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
-              -o UserKnownHostsFile=/dev/null \
-              debian@$primary python3 buffer.py
+              -o UserKnownHostsFile=/dev/null -rp tools \
+              debian@$primary:.
+
+      - name: Log github actions buffering status
+        run: |
+          . ${GITHUB_WORKSPACE}/ci-environment.sh
+          cd ${GITHUB_WORKSPACE}/shakenfist
+          tools/run_remote ${primary} python3 tools/buffer.py
 
       - name: Run getsf installer on primary
         run: |
@@ -77,7 +79,7 @@ jobs:
 
           . ${GITHUB_WORKSPACE}/ci-environment.sh
           ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
-              debian@$primary 'sudo chmod ugo+r /etc/sf/sfrc /etc/sf/shakenfist.json /var/log/syslog'
+              debian@$primary 'sudo chmod ugo+r /etc/sf/* /var/log/syslog'
 
           count=0
           while [ $count -lt 60 ]
@@ -124,6 +126,7 @@ jobs:
           echo ""
 
       - name: Run functional tests
+        timeout-minutes: 120
         run: |
           . ${GITHUB_WORKSPACE}/ci-environment.sh
           scp -rp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
@@ -131,93 +134,61 @@ jobs:
               $source_path/shakenfist \
               debian@$primary:shakenfist
           ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
-              debian@$primary "cd shakenfist/deploy; . /etc/sf/sfrc; sudo pip3 install -r requirements.txt; stestr run --concurrency=5"
+              debian@$primary "cd shakenfist/deploy; . /etc/sf/sfrc; sudo pip3 install -r requirements.txt; set -e; stestr run --concurrency=5; stestr slowest"
 
       - name: Check logs
-        if: ${{ ! cancelled() }}
+        if: always()
         run: |
           . ${GITHUB_WORKSPACE}/ci-environment.sh
-          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no \
-                -o UserKnownHostsFile=/dev/null \
-                debian@$primary sudo chmod ugo+r /var/log/syslog
-          scp -rp -i /srv/github/id_ci -o StrictHostKeyChecking=no \
-              -o UserKnownHostsFile=/dev/null \
-              debian@$primary:/var/log/syslog \
-              ${GITHUB_WORKSPACE}/syslog
+          cd ${GITHUB_WORKSPACE}/shakenfist
+          tools/run_remote ${primary} sudo /home/${baseuser}/tools/ci_event_checks.sh
 
-          failures=0
+      # On Ubuntu 22.04 the cleaner is rated a CPU hog because of etcd cleanup
+      # cost. That's not really something we can control, so just ignore the CPU
+      # usage of that process instead.
+      - name: Check SF process CPU usage
+        if: always()
+        run: |
+          . ${GITHUB_WORKSPACE}/ci-environment.sh
+          ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
+              debian@$primary '. /etc/sf/sfrc; sf-client node cpuhogs --ignore sf_cleaner'
 
-          echo
-          etcd_conns=`grep -c "Building new etcd connection" ${GITHUB_WORKSPACE}/syslog || true`
-          echo "This CI run created $etcd_conns etcd connections."
-          if [ $etcd_conns -gt 5000 ]; then
-            echo "FAILURE: Too many etcd clients!"
-            failures=1
-          fi
+      - name: Check for reasonable data rates
+        if: always()
+        run: |
+          . ${GITHUB_WORKSPACE}/ci-environment.sh
+          cd ${GITHUB_WORKSPACE}/shakenfist
+          tools/run_remote ${primary} sudo /home/${baseuser}/tools/ci_event_checks.sh
 
-          FORBIDDEN=("Traceback (most recent call last):"
-                     "ERROR sf"
-                     " died"
-                     "Extra vxlan present"
-                     "Fork support is only compatible with the epoll1 and poll polling strategies"
-                     "not using configured address"
-                     "Dumping thread traces"
-                     "because it is leased to"
-                     "not committing online upgrade"
-                     "Received a GOAWAY with error code ENHANCE_YOUR_CALM"
-                     "ConnectionFailedError")
-          IFS=""
-          for forbid in ${FORBIDDEN[*]}
-          do
-            if [ `grep -c "$forbid" ${GITHUB_WORKSPACE}/syslog || true` -gt 0 ]
-            then
-              echo "FAILURE: Forbidden string found in logs: $forbid"
-              failures=1
-            fi
-          done
+      - name: Fetch and tweak inventory
+        if: always()
+        run: |
+          . ${GITHUB_WORKSPACE}/ci-environment.sh
+          scp -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
+              debian@$primary:/etc/sf/inventory.yaml /srv/github/
+          sed -i 's|/root/.ssh|/home/debian/.ssh|g' /srv/github/inventory.yaml
 
-          if [ $failures -gt 0 ]; then
-              echo "...failures detected."
-              exit 1
-          fi
+          echo "====="
+          cat /srv/github/inventory.yaml
 
       - name: Gather logs
-        if: ${{ ! cancelled() }}
+        if: always()
         run: |
           set -x
-          . ${GITHUB_WORKSPACE}/ci-environment.sh
 
-          cd ${GITHUB_WORKSPACE}
-          rm -rf artifacts bundle
-          mkdir -p artifacts bundle
+          # We need the ssh key in the place ansible expects it to be, which isn't
+          # true on the CI worker node.
+          cp /srv/github/id_ci /home/debian/.ssh/id_rsa
+          cp /srv/github/id_ci.pub /home/debian/.ssh/id_rsa.pub
 
-          echo "=============================="
-          for node in $nodes
-          do
-            echo "=== $node ==="
-            safe_node=$(echo $node | tr "-" "_")
+          ansible-playbook -i /srv/github/inventory.yaml \
+              --extra-vars "base_image_user=debian ansible_ssh_common_args='-o StrictHostKeyChecking=no'" \
+              ${GITHUB_WORKSPACE}/shakenfist/deploy/ansible/ci-gather-logs.yml
 
-            ssh -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
-                debian@${!safe_node} sudo /srv/shakenfist/venv/bin/clingwrap gather \
-                --target /srv/shakenfist/venv/share/clingwrap/shakenfist-ci-failure.cwd --output /tmp/$node.zip
-            scp -i /srv/github/id_ci -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
-                debian@${!safe_node}:/tmp/$node.zip bundle/
-
-            mkdir -p bundle/$node
-
-            # We ignore the exit code of unzip, as it will return 1 if a warning is
-            # emitted during expansion, even though expansion worked correctly. For
-            # example stripping a leading / from paths.
-            unzip -q bundle/$node.zip -d bundle/$node/ || true
-            rm bundle/$node.zip
-          done
-
-          zip -rq artifacts/bundle.zip bundle/*
-
-      - uses: actions/upload-artifact@v3
-        if: ${{ ! cancelled() }}
+      - uses: actions/upload-artifact@v4
+        if: always()
         with:
           name: bundle.zip
           retention-days: 90
           if-no-files-found: error
-          path: ${{ github.workspace }}/artifacts/bundle.zip
+          path: /srv/github/artifacts/bundle.zip
